version: '3'

services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - scylla_net
    restart: unless-stopped

volumes:
  scylla_data:

networks:
  scylla_net:
    driver: bridge
